x11_based_systems = {
    "Mint": "sudo apt-get install xclip",
    "MX Linux": "sudo apt-get install xclip",
    "openSUSE": "sudo zypper install xclip",
    "Manjaro": "sudo pacman -S xclip",
    "Debian": "sudo apt-get install xclip",
    "EndeavourOS": "sudo pacman -S xclip",
    "Fedora": "sudo dnf install xclip",
    "Ubuntu": "sudo apt-get install xclip",
    "Garuda": "sudo pacman -S xclip",
    "Pop!_OS": "sudo apt-get install xclip",
    "Zorin": "sudo apt-get install xclip",
    "Arch": "sudo pacman -S xclip",
    "Solus": "sudo eopkg install xclip",
    "Artix": "sudo pacman -S xclip",
    "Void": "sudo xbps-install -S xclip",
    "elementary": "sudo apt-get install xclip",
    "Q4OS": "sudo apt-get install xclip",
    "Devuan": "sudo apt-get install xclip",
    "KDE neon": "sudo apt-get install xclip",
    "Slackware": "sudo slapt-get --install xclip",
    "Lite": "sudo apt-get install xclip",
    "deepin": "sudo apt-get install xclip",
    "Mageia": "sudo dnf install xclip",
    "antiX": "sudo apt-get install xclip",
    "PCLinuxOS": "sudo apt-get install xclip",
    "ArcoLinux": "sudo pacman -S xclip",
    "Kubuntu": "sudo apt-get install xclip",
    "SparkyLinux": "sudo apt-get install xclip",
    "Peppermint": "sudo apt-get install xclip",
    "Ubuntu MATE": "sudo apt-get install xclip",
    "Mabox": "sudo apt-get install xclip",
    "Bodhi": "sudo apt-get install xclip",
    "FreeBSD": "sudo pkg install xclip",
    "NixOS": "sudo nix-env -iA nixos.xclip",
    "Robolinux": "sudo apt-get install xclip",
    "Puppy": "sudo apt-get install xclip",
    "AlmaLinux": "sudo yum install xclip",
    "Gentoo": "sudo emerge xclip",
    "Archcraft": "sudo pacman -S xclip",
    "Xubuntu": "sudo apt-get install xclip",
    "Kodachi": "sudo apt-get install xclip",
    "Feren": "sudo apt-get install xclip",
    "Lubuntu": "sudo apt-get install xclip",
    "OpenMandriva": "sudo urpmi xclip",
    "Parrot": "sudo apt-get install xclip",
    "RebornOS": "sudo pacman -S xclip",
    "GhostBSD": "sudo pkg install xclip",
    "LXLE": "sudo apt-get install xclip",
    "siduction": "sudo apt-get install xclip",
    "Qubes": "sudo apt-get install xclip",
    "NomadBSD": "sudo pkg install xclip",
    "Elive": "sudo apt-get install xclip",
    "Alpine": "sudo apk add xclip",
    "Pardus": "sudo apt-get install xclip",
    "OpenBSD": "sudo pkg_add xclip",
    "BunsenLabs": "sudo apt-get install xclip",
    "TUXEDO": "sudo apt-get install xclip",
    "Salix": "sudo slapt-get --install xclip",
    "EasyOS": "sudo apt-get install xclip",
    "Ubuntu Budgie": "sudo apt-get install xclip",
    "Emmabuntüs": "sudo apt-get install xclip",
    "AV Linux": "sudo apt-get install xclip",
    "Trisquel": "sudo apt-get install xclip",
    "ROSA": "sudo apt-get install xclip",
    "KaOS": "sudo pacman -S xclip",
}